  steps:
  - name: maven:3-jdk-8
    entrypoint: mvn
    args: ['--version']
    
 steps:
 - name: maven:3-jdk-8
   entrypoint: mvn
   args: ['test']
  
steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-central1-docker.pkg.dev/sapient-terrain-334911/cloud-build/cloud-spanner-build:$SHORT_SHA', '--build-arg=JAR_FILE=target/build-artifact', '.']
images: ['us-central1-docker.pkg.dev/sapient-terrain-334911/cloud-build/cloud-spanner-build:$SHORT_SHA']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 
           'gus-central1-docker.pkg.dev/sapient-terrain-334911/cloud-build/cloud-spanner-build:$SHORT_SHA']

